### ISSUE TITLE
Request to Open Source Backend Code

### ISSUE THREAD

**Issue by wengsy150943** [xiutangzju/dlbd#1]
Dear DLBD Project Team,

I am interested in detecting database bugs, and I want to express my appreciation for the incredible work you've done. As per the project's introduction, DLBD demonstrates an innovative approach to logic bug detection in databases, and the backend code plays a crucial role in it. Therefore, I wanted to understand this work through the details of the implementation, but I found that the open source code contains only a part of the techniques mentioned in the paper. 

So, I would like to know if the code for other parts of the backend, such as query generation, will be made public subsequently, or there will be another way for me to get the full source code for this work?

Thank you for considering this request.

Best regards，

Wengsy

**Comment by xiutangzju** [comment]
Dear Wengsy,

Thank you for your interest in our work and your kind words regarding the DLBD project. We appreciate your enthusiasm for our efforts to detect database bugs.

We're pleased to inform you that the backend code, including the parts such as query generation, will indeed be made public in the near future. We understand the importance of sharing the full source code for a comprehensive understanding of our work, and we are working diligently to make it accessible to the community.

Your support and interest are valuable to us, and we look forward to sharing the complete implementation with you and the wider audience.

Thank you again for your attention and support.

Best regards,

 DLBD Project Team
